spring:
  application:
    name: travel-agent

semantic-kernel:
  default-model: gpt-41-agia-ai-poc-westus
  openai:
    api-key: 75torbMyLr9T67hbSgctkKukNuUAYdw7kFntrJ0DtkDseMYEVwu0JQQJ99BJAC4f1cMXJ3w3AAAAACOGKZ8S
    endpoint: https://rs-agia-ai-poc-westus.cognitiveservices.azure.com/
